# Generated by Django 2.0.2 on 2018-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_auto_20180222_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='melon Artist ID'),
        ),
    ]
