# Generated by Django 2.0.2 on 2018-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0011_song_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='melon Album ID'),
        ),
    ]
