# Generated by Django 2.0.2 on 2018-02-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0013_auto_20180222_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
