# Generated by Django 2.0.2 on 2018-02-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_song_date',
        ),
    ]
