# Generated by Django 2.0.2 on 2018-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20180221_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_song_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
