# Generated by Django 2.0.2 on 2018-02-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_song_release_song_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=50, null=True, verbose_name='아티스트'),
        ),
    ]
