# Generated by Django 2.0.2 on 2018-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='artist list'),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(blank=True, upload_to='album', verbose_name='커버 이미지'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='앨범명'),
        ),
    ]
