# Generated by Django 2.0.2 on 2018-02-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180208_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(to='artist.Artist', verbose_name='아티스트 목록'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=50, verbose_name='앨범명'),
        ),
    ]
