# Generated by Django 2.0.2 on 2018-02-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20180220_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='blood_type',
            field=models.CharField(blank=True, choices=[(('a',), 'A형'), (('b',), 'B형'), (('c',), 'AB형'), (('o',), 'O형'), (('x',), '기타')], max_length=1, verbose_name='혈액형'),
        ),
    ]
