# Generated by Django 2.0.2 on 2018-02-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20180222_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A형'), ('B', 'B형'), ('C', 'AB형'), ('O', 'O형'), ('X', '기타')], max_length=1, verbose_name='혈액형'),
        ),
    ]
